# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SiteWhereSDK' do
platform :ios, '8.0'
pod 'MQTTKit'
pod 'Protobuf', '3.0.0-alpha-4.1'
end

